### PR TITLE
Re-enable tests

### PR DESCRIPTION
**Pull request by junghans**

### CODE REVIEW

**Comment by junghans** [comment]
@JensWehner @JoshuaSBrown it looks like `unit_test_sphere_lebedev_rule` cannot be build on ubuntu....

```
[ 99%] Built target unit_test_sphere_lebedev_rule


No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```
Some further inveestigation is needed, luckly you can run travis locally:
https://stackoverflow.com/questions/21053657/how-to-run-travis-ci-locally

**Comment by JensWehner** [comment]
I ll look into it.

Cheers Jens

**Comment by JensWehner** [comment]
I could not really reproduce the error. It is not the linking with `unit_test_sphere_lebedev_rule` in general. 

@JoshuaSBrown `unit_bead_structure class` throws a memory leak with gcc4.9.2. . With gcc5.4 it does not

**Comment by junghans** [comment]
Yeah, it must be a problem with `gcc-4.9.2`.

**Comment by JensWehner** [comment]
So basically 4.8 does not work because of regex and 4.9 does notwork for unordered map. So gcc>5 now?

**Comment by junghans** [comment]
Let's give it a try...

**Comment by JensWehner** [comment]
gcc5.0 has no ubuntu ppa for 14.04

**Comment by JensWehner** [comment]
so we would have to go to the trusty version in travis

**Comment by JensWehner** [comment]
So we have to get gcc5.0 from somewhere

**Comment by junghans** [comment]
Isn't that part of `ubuntu-toolchain-r-test`? (from https://docs.travis-ci.com/user/languages/cpp/)

**Comment by JensWehner** [comment]
ohh yeah good point.

**Pull request merged**
